### ISSUE TITLE
problems when build roms for samsung j4 primelte

### ISSUE THREAD

**Issue by Rudi021** [MacTavishAO/android_device_samsung_j4primelte#1]
HI MacTavishAO.i have a problem when build roms with your device tree,vendor and kernel.compile rom to about 80% and when start build apps i always get error about : FAILED: /home/rudi/xenon/out/target/common/obj/APPS/Dialer Intermediates/classes-full-debug.jar and bunch of text.i try many times again and always stop on this.sometimes be other like settings or systemui but always stop there.i try many solutions but none works. maybe you have idea what is wrong.? thanks.

**Comment by MacTavishAO** [comment]
Seems like ROM sources problem to me.

**Comment by Rudi021** [comment]
ok.thanks.i will do repo sync.thanks.
