### ISSUE TITLE
A typo in the JSON file that makes it invalid

### ISSUE THREAD

**Issue by galaxy4public** [MacTavishAO/android_device_samsung_j4primelte#3]
https://github.com/MacTavishAO/android_device_samsung_j4primelte/blob/lineage-17.1/lineage.dependencies#L8 - this line has an extraneous `,` at the end and fails the JSON validation.

**Comment by SebaUbuntu** [comment]
A PR is much appreciated

**Comment by MacTavishAO** [comment]
Create a a pull request.

**Comment by galaxy4public** [comment]
Well, I eventually most likely will, but at this time I just don't have any incentive to fork, fix, test, and submit a PR to something I spotted while I was surfing through GH to see what's going on around MSM8917 support for Android.

**Comment by SebaUbuntu** [comment]
Ok, I'll make it

**Comment by SebaUbuntu** [comment]
https://github.com/MacTavishAO/android_device_samsung_j4primelte/pull/4

**Comment by SebaUbuntu** [comment]
Commit merged, you can close this issue
